name: tara
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - debugpy=1.8.11=py310h6a678d5_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.16=h5eee18b_0
  - pip=25.1=pyhc872135_2
  - python=3.10.16=he870216_1
  - readline=8.2=h5eee18b_0
  - setuptools=78.1.1=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.45.1=py310h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.3.0
      - accelerate==1.7.0
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.7
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - anyio==4.9.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - bitsandbytes==0.46.0
      - certifi==2025.4.26
      - cffi==1.17.1
      - charset-normalizer==3.4.2
      - click==8.2.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - datasets==3.6.0
      - diffusers==0.34.0.dev0
      - dill==0.3.8
      - docker-pycreds==0.4.0
      - exceptiongroup==1.3.0
      - fastapi==0.115.12
      - ffmpy==0.5.0
      - filelock==3.18.0
      - fire==0.7.0
      - flatbuffers==25.2.10
      - fonttools==4.58.2
      - frozenlist==1.6.2
      - fsspec==2025.3.0
      - ftfy==6.3.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - gradio==5.31.0
      - gradio-client==1.10.1
      - groovy==0.1.2
      - grpcio==1.71.0
      - h11==0.16.0
      - hf-xet==1.1.2
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.32.2
      - idna==3.10
      - importlib-metadata==8.7.0
      - jax==0.6.1
      - jaxlib==0.6.1
      - jinja2==3.1.6
      - kiwisolver==1.4.8
      - lora-diffusion==0.1.7
      - markdown==3.8
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.3
      - mdurl==0.1.2
      - mediapipe==0.10.21
      - ml-dtypes==0.5.1
      - mpmath==1.3.0
      - multidict==6.4.4
      - multiprocess==0.70.16
      - networkx==3.4.2
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - open-clip-torch==2.32.0
      - opencv-contrib-python==4.11.0.86
      - opencv-python==4.11.0.86
      - opt-einsum==3.4.0
      - orjson==3.10.18
      - packaging==25.0
      - pandas==2.2.3
      - peft==0.15.2
      - pillow==11.2.1
      - platformdirs==4.3.8
      - propcache==0.3.1
      - protobuf==4.25.8
      - psutil==7.0.0
      - pyarrow==20.0.0
      - pycparser==2.22
      - pydantic==2.11.5
      - pydantic-core==2.33.2
      - pydub==0.25.1
      - pygments==2.19.1
      - pyparsing==3.2.3
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - rich==14.0.0
      - ruff==0.11.11
      - safehttpx==0.1.6
      - safetensors==0.5.3
      - scipy==1.15.3
      - semantic-version==2.10.0
      - sentencepiece==0.2.0
      - sentry-sdk==2.29.1
      - setproctitle==1.3.6
      - shellingham==1.5.4
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - socksio==1.0.0
      - sounddevice==0.5.2
      - starlette==0.46.2
      - sympy==1.14.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - termcolor==3.1.0
      - timm==1.0.15
      - tokenizers==0.21.1
      - tomlkit==0.13.2
      - torch==2.7.0
      - torchvision==0.22.0
      - tqdm==4.67.1
      - transformers==4.52.3
      - triton==3.3.0
      - typer==0.16.0
      - typing-extensions==4.13.2
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.4.0
      - uvicorn==0.34.2
      - wandb==0.19.11
      - wcwidth==0.2.13
      - websockets==15.0.1
      - werkzeug==3.1.3
      - xformers==0.0.30
      - xxhash==3.5.0
      - yarl==1.20.0
      - zipp==3.22.0